 services:
   historiamedica123:
     build: ./HistoriaClinica
     ports:
       - 8080:8080
   demo123:
     build: ./Demo
     ports:
       - 8081:3000
   app123:
     build: ./app
     ports:
       - 8082:8000
