 services:
   historiamedica123:
     build: ./HistoriaClinica
     ports:
       - 8080:8080
     env_file:
       - ./.env
   demo123:
     build: ./Demo
     ports:
       - 8081:3000
     env_file:
       - ./.env
   app123:
     build: ./app
     ports:
       - 8082:8000
     env_file:
       - ./.env
