 services:
    agendarcita:
     build: ./AgendarCita
     ports:
       - 8083:4000
   historiamedica:
     build: ./HistoriaClinica
     ports:
       - 8080:8080
     env_file:
       - ./.env
   doctores:
     build: ./Demo
     ports:
       - 8081:3000
     env_file:
       - ./.env
   pacientes:
     build: ./app
     ports:
       - 8082:8000
     env_file:
       - ./.env
